### ISSUE TITLE
The addon appears in all node editors. 

### ISSUE THREAD

**Issue by MarioPeper** [Correct-Syntax/Blender-Gimel-Studio-Addon#1]
In the compositor editor it is certainly good but in the render and image editor it also makes sense. In shader editor it only makes sense if you can edit images directly from shader editor.

**Comment by Correct-Syntax** [comment]
You're right. I guess I didn't catch this during my testing. Thank you!

**Comment by Correct-Syntax** [comment]
@MarioPeper, I have been unable to figure out a way to only place the panel in the compositor as doing `bl_space_type = 'NODE_EDITOR'` doesn't specify a specific node editor. I can ask a blender dev/post somewhere, but I though I would first ask you:

**Do you know of any other blender addons that might have this "issue solved"? (as in, the addon's panel appears only in the compositor)** All the addons I could find appeared in both the compositor and shader editor. Obviously, the Gimel Studio addon doesn't make sense in both -as you said.

**Comment by MarioPeper** [comment]
In fact, I didn't find anything about it either. Other addons behave in the same way. I just haven't noticed it yet because I collect all addons I don't need that often in one Tab e.g. Misc.
Maybe someone at Blenderartis from the coding section can help.
